[package]
name = "devicon-lookup"
description = "Prepend the correct devicon to the beginning of each filename"
version = "0.1.0"
authors = ["Corey Alexander <coreyja@gmail.com>"]
repository = "https://github.com/coreyja/devicon-lookup"
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
